#!/usr/bin/perl

use CGI qw(:standard);
use JSON;
use Date::Calc qw(Day_of_Week);
use String::Random;
my $sr = String::Random->new;
my $random = $sr->randregex('[a-z]{8}');

&make_date(86400);
my $datestamp =  sprintf("%4d-%02d-%02d",$thisyear,$mon,$mday);
my $wday = &find_weekday($datestamp);
my $mo = &find_month($mon);
my $exp = "$wday, ".$mday."-".$mo."-".$thisyear." $thistime:$thissec GMT";

#print "Set-Cookie:session = $random;Expires = $exp;Path = /;SameSite = None;Secure;HttpOnly;\n";

print "Content-type:application/json; charset=UTF-8\r\n\r\n";
#print header('application/json');

my $curip = $ENV{'REMOTE_ADDR'};

#my %hash = ('ip' => $curip);
#my $j = encode_json(\%hash);
#$j = "callback({\"ip\":\"$curip\"});";
#print $j;

print $curip;

exit;

sub make_date { #33

my $addedtime = shift;
my $t; my $this_;
    ($thissec,$thismin,$thishour,$mday,$mon,$thisyear,$t,$t,$t) = gmtime(time+$addedtime);
    $mon++;
	my $month = $months[$mon];
	     $month = $$month if $$month;
    $thisyear += 1900;
    $current_date = "$mday $month $thisyear";
    $current_date = "$month $mday, $thisyear" if ($language eq "english");

    if ($mday >= 10 && $mon >= 10 ) { $this_ = "$mon/$mday";}
    elsif ($mon >= 10) { $this_ = "$mon/0$mday";}
    elsif ($mday >= 10) { $this_ = "0$mon/$mday";}
    else { $this_ = "0$mon/0$mday";}
    
    $thissec = '0'.$thissec if ($thissec < 10);

	$thisdate = "$thisyear/$this_";
    
    if ($thishour >= 10 && $thismin >= 10 ) { $thistime = "$thishour:$thismin";}
    elsif ($thishour >= 10) { $thistime = "$thishour:0$thismin";}
    elsif ($thismin >= 10) { $thistime = "0$thishour:$thismin";}
    else { $thistime = "0$thishour:0$thismin";}
}

sub find_weekday { #144

my $td = shift;

$td =~ /^(\d+)-(\d+)-(\d+)/;
my $y = $1;
my $m = $2;
my $d = $3;

my $wd = Day_of_Week($y, $m, $d);
$wd = 0 if ($wd eq '7');

@weekday = ("Sunday","Monday","Tuesday","Wednesday","Thursday","Friday","Saturday");

return $weekday[$wd];
}

sub find_month { #144

my $m = shift;

@mo_abbr = ('',"Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec");

return $mo_abbr[$m];
}

