#!/usr/bin/perl

#   Copyright (c) 2007 Alex Shevlakov info[at]motivation[dot]ru
#   All Rights Reserved.

#   This program is free software; you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation; either version 2 of the License, or
#   (at your option) any later version.
#
#   This program is distributed in the hope that it will be useful,
#   but WITHOUT ANY WARRANTY; without even the implied warranty of
#   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#   GNU General Public License for more details.
use CGI;

$pref_lang = "en" 
#if ($scriptURL =~ /bjon/)
;

my %Cookies = GetCookies('LANG');

my $lang = $Cookies{'LANG'} eq '' ? $pref_lang : $Cookies{'LANG'};

do ('./cp_'.$lang);

sub GetCookies {

     my @cookieList = @_;

     my $query = new CGI;

     my %Cookies;

     foreach my $name (@cookieList) {

          $Cookies{$name} = $query->cookie($name);
     }

     return %Cookies;
};
